repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        description: Trims trailing whitespace
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline
      - id: check-yaml
        description: Attempts to load all yaml files to verify syntax
      - id: check-json
        description: Attempts to load all json files to verify syntax
      - id: check-toml
        description: Attempts to load all TOML files to verify syntax
      - id: check-xml
        description: Attempts to load all xml files to verify syntax
      - id: debug-statements
        description: Check for debugger imports and py37+ breakpoint() calls
      - id: check-builtin-literals
        description: Require literal syntax when initializing empty or zero Python builtin types
      - id: check-case-conflict
        description: Check for files with names that would conflict on a case-insensitive filesystem
      - id: check-docstring-first
        description: Checks for a common error of placing code before the docstring
      - id: check-merge-conflict
        description: Check for files that contain merge conflict strings
      - id: check-executables-have-shebangs
        description: Checks that non-binary executables have a proper shebang
      - id: mixed-line-ending
        description: Replaces mixed line endings automatically with the most frequent line ending

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        name: Format Python code
        description: The uncompromising Python code formatter
        language_version: python3.12
        args: [--line-length=88]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sort Python imports
        description: Library to sort imports alphabetically, and automatically separated into sections
        args: [--profile=black, --line-length=88]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Lint Python code
        description: Your Tool For Style Guide Enforcement

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: Lint YAML files
        description: A linter for YAML files
        args: [-d, relaxed]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        name: Format JSON, YAML, Markdown
        description: Prettier is an opinionated code formatter
        types_or: [json, yaml, markdown]
